apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dashy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dashy
    spec:
      containers:
        - name: dashy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.config.path }}
              subPath: conf.yaml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
