image:
  repository: dariusgroza16/homelab-fe
  tag: latest
  pullPolicy: Always  

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: k3s.suirad.dev
  path: /
  pathType: Prefix
