image:
  repository: lissy93/dashy
  tag: latest
  pullPolicy: Always  

config:
  path: /etc/dashy/conf.yaml

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: dashy.local
  path: /
  pathType: Prefix
